In [8]:
# CTRL + ENTER : Running cell namun tidak berpindah ke cell berikutnya

# SHIFT + ENTER : Running cell dan pindah ke cell berikutnya (jika ada)
# Jika tidak ada, maka akan bikin cell baru

# ALT + ENTER : Running cell dan membuat cell baru setelahnya


[1, 2, 3, 4]


# Numpy Array

In [2]:
# Digunakan untuk mengolah sebuah array / list
# Array 1 dimensi : Vector --> [1,2,3,4,5,6]
# Array 2 dimensi : Matrics --> [[1, 2, 3], ['a', 'b', 'c']]
import numpy as np

In [19]:
# Mengubah list 1-d menjadi array 1-d (Vector)
numbers = [1, 2, 3, 4, 5]
arrNumbers = np.array(numbers)
print(arrNumbers)

[1 2 3 4 5]


In [24]:
# Mengubah list 2-d menjadi array 2-d (Matrics)
numbers = [[1,2,3], [4, 5,6], [7,8,9]]
arrNumbers = np.array(numbers)
print(arrNumbers)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


> arange

In [3]:
# Membuat sebuah array  0 - 9
arrRange = np.arange(10)
print(arrRange)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Membuat sebuah array  1 - 10 
arrRange = np.arange(1, 11)
print(arrRange)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# Membuat sebuah array nilai genap 0 - 10
arrRange = np.arange(0,11,2)
print(arrRange)

[ 0  2  4  6  8 10]


In [7]:
arrRange = np.arange(10,0,-1)
print(arrRange) # [10  9  8  7  6  5  4  3  2  1]

arrRange = np.arange(10,0,-2)
print(arrRange) # [10  8  6  4  2]

[10  9  8  7  6  5  4  3  2  1]
[10  8  6  4  2]


> linspace

In [10]:
# Dari 0 - 10, sebanyak 2 angka
arrLin = np.linspace(0,10,2)
print(arrLin)

[ 0. 10.]


In [8]:
# Dari 0 - 10, sebanyak 5 angka
arrLin = np.linspace(0,10,5)
print(arrLin)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
# Dari 0 - 10, sebanyak 10 angka
arrLin = np.linspace(1,10,10)
print(arrLin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


random.randint

In [82]:
# Random integer dari 1 - 10, sebanyak 1 data
randInt = np.random.randint(1, 11)
print(randInt)

9


In [102]:
# Random integer dari 1 - 10, sebanyak 7 data
randInt = np.random.randint(1,11,7)
print(randInt)

[10  5  6  1 10  8  9]


> shape and reshape

In [144]:
# shape digunakan untuk melihat  bentuk array
arrRange = np.arange(1,7)
print(arrRange)
print(arrRange.shape)

[1 2 3 4 5 6]
(6,)


In [145]:
# reshape digunakan untuk mengubah bentu array
# reshape(2, 3) --> Mengubah bentuk menjadi 2 baris 3 kolom
arrRange = arrRange.reshape(2, 3)
print(arrRange)

[[1 2 3]
 [4 5 6]]


In [148]:
# reshape 3 baris 2 kolom
arrRange = arrRange.reshape(3, 2)
print(arrRange)

[[1 2]
 [3 4]
 [5 6]]


In [150]:
arrRange = arrRange.reshape(6)
print(arrRange)

[1 2 3 4 5 6]


> max() and min()

In [122]:
# Random dari 0 - 49, sebanyak 10 data
arrInt = np.random.randint(0, 50, 10)
print(arrInt)

[13 11 16 25 39 12 47 30 22 44]


In [123]:
maxInt = arrInt.max()
print(maxInt)

47


In [125]:
arrInt.min()

11

In [130]:
arrRange = np.arange(1,26)
arrRange = arrRange.reshape(5,5)
print(arrRange)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [133]:
print('Nilai Max :',arrRange.max())
print('Nilai Min :',arrRange.min())

Nilai Max : 25
Nilai Min : 1


In [135]:
print(arrRange)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [142]:
print(arrRange[1])
print(arrRange[-1])
print(f'Nilai max untuk baris kedua : {arrRange[1].max()}')
print(f'Nilai min untuk baris terakhir : {arrRange[1].min()}')

[ 6  7  8  9 10]
[21 22 23 24 25]
Nilai max untuk baris kedua : 10
Nilai min untuk baris terakhir : 6


In [153]:
from numpy.random import randint

In [154]:
randint(2, 10)

6