In [8]:
# CTRL + ENTER : Running cell namun tidak berpindah ke cell berikutnya

# SHIFT + ENTER : Running cell dan pindah ke cell berikutnya (jika ada)
# Jika tidak ada, maka akan bikin cell baru

# ALT + ENTER : Running cell dan membuat cell baru setelahnya


[1, 2, 3, 4]


# Numpy Array

In [2]:
# Digunakan untuk mengolah sebuah array / list
# Array 1 dimensi : Vector --> [1,2,3,4,5,6]
# Array 2 dimensi : Matrics --> [[1, 2, 3], ['a', 'b', 'c']]
import numpy as np

In [19]:
# Mengubah list 1-d menjadi array 1-d (Vector)
numbers = [1, 2, 3, 4, 5]
arrNumbers = np.array(numbers)
print(arrNumbers)

[1 2 3 4 5]


In [24]:
# Mengubah list 2-d menjadi array 2-d (Matrics)
numbers = [[1,2,3], [4, 5,6], [7,8,9]]
arrNumbers = np.array(numbers)
print(arrNumbers)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


> arange

In [3]:
# Membuat sebuah array  0 - 9
arrRange = np.arange(10)
print(arrRange)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Membuat sebuah array  1 - 10 
arrRange = np.arange(1, 11)
print(arrRange)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# Membuat sebuah array nilai genap 0 - 10
arrRange = np.arange(0,11,2)
print(arrRange)

[ 0  2  4  6  8 10]


In [7]:
arrRange = np.arange(10,0,-1)
print(arrRange) # [10  9  8  7  6  5  4  3  2  1]

arrRange = np.arange(10,0,-2)
print(arrRange) # [10  8  6  4  2]

[10  9  8  7  6  5  4  3  2  1]
[10  8  6  4  2]


> linspace

In [10]:
# Dari 0 - 10, sebanyak 2 angka
arrLin = np.linspace(0,10,2)
print(arrLin)

[ 0. 10.]


In [8]:
# Dari 0 - 10, sebanyak 5 angka
arrLin = np.linspace(0,10,5)
print(arrLin)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
# Dari 0 - 10, sebanyak 10 angka
arrLin = np.linspace(1,10,10)
print(arrLin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
