# Exercise - Numpy

In [1]:
# Import Numpy
import numpy as np

In [2]:
# Buat sebuah array berisi 5 angka nol



array([0., 0., 0., 0., 0.])

In [3]:
# Buat sebuah array berisi 5 angka satu



array([1., 1., 1., 1., 1.])

In [4]:
# Buat sebuah array berisi 5 angka 5



array([5., 5., 5., 5., 5.])

In [6]:
# Buat sebuah array integer dari 10 - 50


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
# Buat sebuah array angka genap dari 10 - 50


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
# Buatlah matrix 3 x 3 dengan nilai 0 - 8


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Buatlah nilai random antara 0 - 1


array([0.20178905])

In [11]:
# Buatlah matriks 25 angka random


array([ 0.46723079, -0.81247604,  0.08949635,  1.27997385, -0.60490566,
        0.14874374, -0.24265212, -0.5787221 , -2.18633815, -1.39985376,
       -0.18260267, -0.83938334,  0.41866845, -0.39285142, -0.48043054,
        0.17856887,  0.54240526,  0.26291282,  0.46154263, -0.24752132,
        1.55740075, -0.16095496,  0.99123665,  0.39212677, -1.95301549])

In [13]:
# Array 2 dimensi / Matriks dengan nilai 0.01 - 1


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
# Buatlah array dengan angka 0 - 1 sebanyak 20, dengan jarak setiap digitnya sama


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
# Buat kode untuk menghasilkan result seperti dibawah


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
# Buat kode untuk menghasilkan result seperti dibawah


20

In [18]:
# Buat kode untuk menghasilkan result seperti dibawah


array([[ 2],
       [ 7],
       [12]])

In [19]:
# Buat kode untuk menghasilkan result seperti dibawah


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])